# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('borrow_num', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=20)),
                ('deposit', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
