# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='borrow_limit',
        ),
    ]
