# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_administrator_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='authority',
            field=models.BooleanField(),
        ),
    ]
