# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_libroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
