# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_libroot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroot',
            name='authority',
            field=models.CharField(max_length=1),
        ),
    ]
