# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBook',
            fields=[
                ('book_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('total_num', models.IntegerField()),
                ('available_num', models.IntegerField()),
                ('book_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowOrder',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('borrow_time', models.DateTimeField()),
                ('debt', models.IntegerField(default=0)),
                ('return_time', models.DateTimeField()),
                ('is_return', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_order_book', to='librarian.AllBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_order_user', to='reader.User')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('borrow_time', models.DateTimeField()),
                ('successful', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_order_user', to='librarian.AllBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_order_user', to='reader.User')),
            ],
        ),
        migrations.AddField(
            model_name='allbook',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_book_isbn', to='librarian.Book'),
        ),
    ]
