# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbook',
            name='the_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_book_isbn', to='librarian.Book'),
        ),
        migrations.AlterField(
            model_name='borroworder',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_order_book', to='librarian.AllBook'),
        ),
        migrations.AlterField(
            model_name='borroworder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_order_user', to='reader.User'),
        ),
        migrations.AlterField(
            model_name='reserveorder',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_order_book', to='librarian.AllBook'),
        ),
        migrations.AlterField(
            model_name='reserveorder',
            name='the_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_order_isbn', to='librarian.Book'),
        ),
        migrations.AlterField(
            model_name='reserveorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_order_user', to='reader.User'),
        ),
    ]
