# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_auto_20181106_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdelhistory',
            name='book_isbn',
            field=models.IntegerField(null=True),
        ),
    ]
