# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_auto_20181106_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbook',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
