# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-05 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_auto_20181005_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pubdate',
        ),
    ]
