# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_remove_book_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
