# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_reserveorder_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveorder',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_order_book', to='librarian.AllBook'),
        ),
        migrations.AlterField(
            model_name='reserveorder',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_order_isbn', to='librarian.Book'),
        ),
    ]
