# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_auto_20181006_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default='100', max_length=100),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserveorder',
            name='expire',
            field=models.BooleanField(default=False),
        ),
    ]
