# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_auto_20181015_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroworder',
            name='last_count_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='borroworder',
            name='return_time',
            field=models.DateTimeField(null=True),
        ),
    ]
