# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-29 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_libroot'),
        ('reader', '0002_remove_user_borrow_limit'),
        ('librarian', '0009_auto_20181022_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUpdateDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_updated', models.BooleanField()),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookDelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_isbn', models.IntegerField()),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=50)),
                ('deleted_time', models.DateTimeField(auto_now_add=True)),
                ('del_reason', models.CharField(choices=[('D', 'DAMAGED'), ('L', 'LOST')], max_length=1)),
                ('librarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_books', to='administrator.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('D', 'DEPOSIT'), ('F', 'FINE')], max_length=1)),
                ('num', models.IntegerField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('librarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_orders', to='administrator.Administrator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_orders', to='reader.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('expire', models.BooleanField()),
                ('issue_time', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notices', to='administrator.Administrator')),
            ],
        ),
    ]
