# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_libroot'),
        ('librarian', '0009_auto_20181022_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('expire', models.BooleanField()),
                ('issue_time', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notices', to='administrator.Administrator')),
            ],
        ),
    ]
