# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-29 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0010_autoupdatedb_bookdelhistory_moneyorder_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='expire',
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='administrator.Administrator'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='notice',
            name='issue_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
