# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_remove_user_borrow_limit'),
        ('administrator', '0004_libroot'),
        ('librarian', '0010_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField()),
                ('num', models.IntegerField()),
                ('order_time', models.DateField(auto_now_add=True)),
                ('teller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MoneyOrder', to='administrator.Administrator')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_Money_order', to='reader.User')),
            ],
        ),
    ]
