# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0011_auto_20181029_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='administrator.Administrator'),
        ),
    ]
