# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0011_moneyorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUpdateDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_updated', models.BooleanField()),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
