# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-28 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0012_autoupdatedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_isbn', models.IntegerField()),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=50)),
                ('deleted_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
