# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0013_auto_20181031_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borroworder',
            name='last_count_time',
        ),
        migrations.AddField(
            model_name='borroworder',
            name='is_alert',
            field=models.BooleanField(default=False),
        ),
    ]
