# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0013_bookdelhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyorder',
            name='teller',
        ),
        migrations.AlterField(
            model_name='moneyorder',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moneyorder',
            name='order_type',
            field=models.CharField(choices=[('D', 'DEPOSIT'), ('F', 'FINE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='moneyorder',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_orders', to='reader.User'),
        ),
    ]
