# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-28 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0014_auto_20181028_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyorder',
            old_name='user_id',
            new_name='user',
        ),
    ]
